// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: nav

#include "../ui.h"

lv_obj_t * uic_Keyboard1;
lv_obj_t * uic_Label2;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -3);
    lv_obj_set_y(ui_Label2, -71);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Xin chào");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_SFProT16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_Screen1);
    lv_obj_set_width(ui_Keyboard1, 300);
    lv_obj_set_height(ui_Keyboard1, 120);
    lv_obj_set_x(ui_Keyboard1, 8);
    lv_obj_set_y(ui_Keyboard1, 64);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    uic_Label2 = ui_Label2;
    uic_Keyboard1 = ui_Keyboard1;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    uic_Label2 = NULL;
    ui_Label2 = NULL;
    uic_Keyboard1 = NULL;
    ui_Keyboard1 = NULL;

}
